#macro TRANSITION_DEPTH -5000
#macro BATTLE_TRANSITION_TIME_S 0.5
#macro BATTLE_TRANSITION_SPINS 1.6
#macro HAT_JUMP_HEIGHT 16

#macro EVENT_FADE_OUT_RATE 0.05
#macro EVENT_JUMP_HEIGHT 16
#macro EVENT_JUMP_TIME_S 0.25

#macro OUT 0
#macro IN 1